"""remove_unique_refresh_token

Revision ID: b40cdb102f68
Revises: 9a0a9c1b9ca4
Create Date: 2026-07-30 10:14:43.816062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b40cdb102f68'
down_revision: Union[str, Sequence[str], None] = '9a0a9c1b9ca4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('refresh_tokens_user_id_key'), 'refresh_tokens', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('refresh_tokens_user_id_key'), 'refresh_tokens', ['user_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
